Add support for HCCS A3000 IDE card
evansm7/riscix_ide pull request #2
Opened 2024-07-03 15:27 UTC by rhalkyard

Decided that I wanted to experience ancient Unix on my A3000, so I hacked in support for the HCCS IDE card that I have in it. Had to make a few modifications in support of this - allowing for the high-byte register to be in different locations for reads and writes, and returning the address of the following sector when probing for an ADFS volume. These shouldn't have any impact on the function of other cards, but I'm not really able to test that.

The Armstrong Walker IDEFS used by the HCCS card has a very simplistic 'partitioning' scheme - it simply has up to 4 ADFS volumes concatenated together, with no partition table. I haven't completely worked out a partitioning tool to create RISCiX partitions in this scheme, but an afternoon with a calculator and a hex editor got me a valid partition table that seems to keep both IDEFS and RISCiX happy.

2024-07-07 20:09 UTC, evansm7 requested changes
Hi Richard,

(Sorry for the delay in looking at this.) I'm really excited to see this work, thank you for doing it!  The logic looks all sound, and cleanups are welcome.  Well done for making this work without net booting too, impressive. :)
Would you please humour me to tweak a couple of small nitpicks/suggestion in a new revision?  All cosmetic but will make it even better.

2024-07-07 20:09 UTC, evansm7 commented on ecide_parts.c
> +        /* Calculate the offset of the sector following the end of volume and
nit: Would be nice to match neighbouring "Linux-ish" comment style, i.e. leading `* ` per comment line and closing `*/` on a newline ✌️

2024-07-07 20:09 UTC, evansm7 commented on ecide_parts.c
> +/* HCCS IDEFS does not have a partition table; it's 'partitioning' scheme is
nit: typo, "its"

2024-07-07 20:09 UTC, evansm7 commented on ecide_parts.c
> +                *out_next_sector_offset = (sector_offset + bb->disc_size / (2 << (bb->log2secsize-1)));
The maths here looks kinda sneaky :-) :-)  But also I have no confidence of Norcroft C folding this properly.  Can I suggest simplifying to:
> *out_next_sector_offset = sector_offset + (bb->disc_size >> bb->log2secsize);

2024-07-08 00:58 UTC, rhalkyard commented
Changes made as requested! Thanks for catching my slip-ups.

2024-07-08 08:49 UTC, merged

2024-07-08 08:49 UTC, evansm7 commented
Thank you, merged! 🤩

2024-11-25 15:23 UTC, MarkYoungIW commented
I have an A3010 with an HCCS Ultimate Expansion in it that also runs Armstrong Walker IDEFS.

Currently I have a 2GB CF partitioned into 4 partitions.

There is very little on the 4th partition, so ideally I would like to make that into my RISCiX drive so to speak, with both the bootstrap and the partition? Any advice would be gratefully recieved.

Thanks

2024-11-26 02:50 UTC, rhalkyard commented
Oooh, that's a good question. In theory I think it should be possible, with a few limitations - the A3010's floppy drive, serial and parallel ports won't work under RISC iX since it has no support for newer machines' PC-style IO, but there's a good chance that it'll still boot to a console and respond to the keyboard and mouse. You'll also need 4MB of RAM - I don't believe RISC iX will boot with less.

I wouldn't be surprised if the Ultimate Expansion has a different podule ID, and its IDE registers might not be mapped the same as the Userport+IDE card that I have. It shouldn't require much in the way of changes to support that, though - if you can send me a `*RMSave`d copy of your `IDEFS` module I can compare it with mine to see where its registers are, and you can run the following in BASIC to get your podule's ID bytes:

```basic
DIM buf% 16
SYS "Podule_ReadHeader",,,buf%,1
PRINT "Product: ", ~(buf%!0 / 65536)
PRINT "Manufacturer: ", ~(buf%!4 AND 65535)
```

Setting up a disc for RISC iX is unfortunately a bit hairy. I did my initial bootstrapping in a modified build of Arculator (I've sent Sarah the patches but she hasn't merged them yet), bodging a RISC iX partition table into the disc image by hand using a hex editor, and then cloning a RISC iX install from the SCSI disc image that's floating around. Writing it up and making a partitioning tool is on my to-do list. If I can find a 'clean' version of the image I built, before I added my own accounts and software to it, I can send you a copy if you'd like to give it a go.

I was only ever able to get RISC iX to boot successfully from the first partition, and this has a few unfortunate consequences. HCCS IDEFS gives up looking for partitions as soon as it sees anything that's not a FileCore volume, so having RISC iX partitions attached to your first partition means that you can't have any more RISC OS partitions. Additionally, the RISC iX boot loader is subject to the same 512MB limitation as RISC OS, so you can't tack RISC iX onto the end of a 512MB RISC OS partition, you've got to divide the 512MB up between them. It might be possible to get the RISC iX boot loader to load from a later partition (RISC iX itself should have no problem with this), but I wasn't able to figure out how.

Anyway, if this hasn't scared you off, do let me know and I'll try and dig up that disc image for you to try!

2024-11-26 10:01 UTC, MarkYoungIW commented
Product: 6300
Manufacturer: C00

IDEFS
https://drive.google.com/file/d/120xcVyaGMSEQgBrJB92nI0w-0ND_jMtS/view?usp=sharing

I will certainly need some guidance, but happy to give it a crack.

2024-11-26 14:35 UTC, rhalkyard commented
It looks like you've got IDE registers at 2D00, and the same high-byte latch arrangement as my card, at 2E00 for write and 2F00 for read. The partition table format looks the same as mine, so once I dig up that disc image, it should be a good starting point.

So you'll want to add a function to `ecide.c` like:
```c
void ecide_init_ultimate(int slot) {
        regs_t podule_regs = (regs_t)XCB_ADDRESS(FAST, slot);
        ecide_init_high(slot, podule_regs + 0x2d00, podule_regs + 0x2e00,
                        podule_regs + 0x2f00, HOST_HCCS);
}
```

and then patch `xcbconf.c` in the RISC iX source tree to add something like:

```c
#define XCB_PRODUCT_HCCS_IDE_ULTIMATE 0x6300
```

and add a corresponding entry to the `xcb_type[]` array such as:

```c
{ { XCB_PRODUCT_HCCS_IDE_ULTIMATE, XCB_COMPANY_HCCS, XCB_COUNTRY_UK}, 0, ecide_init_ultimate, ecide_init_low, ecide_shutdown, 0}
```

2024-11-26 16:52 UTC, MarkYoungIW commented
A little unsure where I am meant to be looking for xcbconf.c.

Thanks

![SRC](https://github.com/user-attachments/assets/7b8a3edf-89b1-4586-88b6-8a1e072a5031)

2024-11-26 17:33 UTC, MarkYoungIW commented
Ignore the above. I have found it.

Thanks
![SRC2](https://github.com/user-attachments/assets/ba92fda9-da54-442c-8f5a-6540ed54ab2a)

2024-12-06 03:50 UTC, rhalkyard commented
Ah, unfortunately you've run into a chicken-and-egg situation - you need a working RISC iX system in order to compile a new kernel with the driver that you need in order to get a working RISC iX system! I got around this by a lot of faffing about with Arculator and an NFS server, but unfortunately in order to get THAT working I had to [fix a networking bug](https://github.com/sarah-walker-pcem/arculator/issues/48) and [add HCCS IDE emulation](https://github.com/sarah-walker-pcem/arculator/pull/47) in Arculator, and I don't believe those changes have been brought into mainline Arculator yet (I should really bother Sarah about that...).

I'm in the middle of a somewhat chaotic move from a falling-to-bits old laptop to a new machine, but once I can get my modified copy of Arculator working again, I'll try to build you a RISC iX image with the IDE driver, and save you having to go down the same rabbit hole that I did.

2024-12-09 16:16 UTC, rhalkyard commented
Right. [riscix-hccs.zip](https://github.com/user-attachments/files/18064301/riscix-hccs.zip) should get you going - I haven't tested it on an A3010, of course, but it boots on my A3000 and has the driver changes discussed above that should in theory support your IDE card. It's only a 512MB image since various IDEFS and RISC iX constraints mean that going any bigger is pointless, but you should still be able to write it to your 2GB drive and have it work.

Once you have booted into RISC OS, you will need to run the following commands to set up the RISC iX boot loader:

```
IDEFS
RMLoad !RISCiX.RISCiXFS
Configure Device id0
Configure Unit 0
Configure Partition 0
```

After that, load `!RISCiX`, click the RISC iX logo in the icon bar, and then click 'OK' to boot. Let me know how it goes - if it works, then we should get those driver changes into a pull request.

In the process of creating that image I documented the whole ordeal of bootstrapping the installation and wrote a tool to partition the disc (instead of hacking it up with a hex editor) - https://github.com/rhalkyard/riscix-hccs if you're curious!

2024-12-09 22:00 UTC, MarkYoungIW commented
Amazing. Thank you. I have got a couple of CF cards free, so will get the image on one of them and give it a go in the next couple of days. I will report back soon.

2024-12-10 10:56 UTC, evansm7 commented
Quickly just wanted to echo thanks not only for extra card support, but for the excellent write up! If you haven’t already (rushing to work…) any chance to post a link to https://github.com/rhalkyard/riscix-hccs to StarDot to join it up?  I’ll dig out my old notes for making the ZIDEFS partitions and see if it can reuse your script (nicer than hacked !HForm). 
I’ll grab your PR; I’m being very slow with home stuff atm.

2024-12-10 15:09 UTC, rhalkyard commented
> Quickly just wanted to echo thanks not only for extra card support, but for the excellent write up! If you haven’t already (rushing to work…) any chance to post a link to https://github.com/rhalkyard/riscix-hccs to StarDot to join it up?

I've been meaning to do exactly that ever since I got it working months ago! The need for a modified Arculator and the lack of a partitioning tool had led me to put it off, but with one of those two, and a simplified Arculator build from my git repo, I think it might be time.

> I’ll dig out my old notes for making the ZIDEFS partitions and see if it can reuse your script (nicer than hacked !HForm).

Feel free to grab anything useful out of it. It's a bit of a dirty hack and somewhat specific to the way Armstrong-Walker IDEFS does things (you carve up the disc in RISC OS with the `!IDEMgr` partitioning tool, and then my tool just turns everything past the first partition into RISC iX), but there's some code in there for reading and writing boot blocks, disc records and RISC iX partition tables that might be useful.

2024-12-10 16:35 UTC, MarkYoungIW commented
OK, first try, it doesn't appear to like the AKF53 monitor I am using, and no matter what monitor type I tried, the screen is rolling. The benefit with the A3010 is it has a TV modulator in it, so fingers crossed that may solve the issue if I did out a telly.

So far it doesn't appear to be booting, I don't know if you can read the attached or not.

![IMG_20241210_162936](https://github.com/user-attachments/assets/c272cd09-49a1-4082-b8fa-e35b662eee16)

2024-12-10 17:58 UTC, rhalkyard commented
Yeah, looks like it's failing to see the partitions - though with the scrambled image it's hard to tell if that's because the IDE driver isn't loading at all (say, if I got your card ID wrong), or if it's loading and then failing to talk to the drive (if I got the register definitions wrong). I'm inclined toward the former, but I'm not 100% sure we're seeing all the messages there. I'll go back and double-check my changes, and build another image with debug messages enabled in the driver that might shed a bit more light on what's going on.

The A3010 has software-controlled sync polarity and VIDC clock. RISC iX wouldn't be aware of that, and might be accidentally putting it into the wrong mode - that could definitely confuse your monitor. On my A3000 I use a modern LCD with my monitor type set to VGA (`Configure MonitorType 3` I think?) and that seems to work - might be worth a try if you've got a suitable adaptor and monitor handy.

2024-12-10 18:00 UTC, MarkYoungIW commented
I will have a look through my boxes of rubbish here and see what I can pull out to try and get the picture stable.

2024-12-10 19:32 UTC, rhalkyard commented
Think I've found the problem - cocked up the endianness of the values returned by that `Podule_ReadHeader` SWI that I had you run, which would mean RISC iX didn't see your IDE card - its product ID is `&0063`, NOT `&6300` as that BASIC snippet reported.

Here's an updated image for you [riscix-hccs.zip](https://github.com/user-attachments/files/18084923/riscix-hccs.zip), I've updated my branch at https://github.com/rhalkyard/riscix_ide/tree/hccs-ultimate-a3k with the corrected ID as well.

2024-12-10 19:52 UTC, rhalkyard commented
Just for good measure in case it still doesn't work, here's an image with debug logging turned on: 
[riscix-hccs-debug.zip](https://github.com/user-attachments/files/18085114/riscix-hccs-debug.zip)

2024-12-11 07:40 UTC, MarkYoungIW commented
OK, I think the new one is loading. I can definitely see drive size. So far though every display I have in the house is doing the same, although I have nothing that modern. I will have a quick look in the free ads etc and see what else I can find to give it a test. I think it's more an issue with my monitors at the moment.

2024-12-11 16:59 UTC, MarkYoungIW commented
OK, I have managed to pick up two flat screen monitors as well, and as soon as it clicks into RISCiX on either of those it goes straight to 'No Signal'. I have tried configuring every monitor type and to no avail unfortunately. The best picture so far is as above on the AKF53 in either monitortype 1 or 3.

I did try a couple of old CRT TVs off the A3010s built in modulator, and both of those were rolling too.

2024-12-11 19:39 UTC, rhalkyard commented
Hmm, that's unfortunate - it's very promising though that it appears to see the drive and, I think, even the partitions! Odd that it resets itself if left alone - I wonder if it's still getting hung up on something and panic-ing later down the line.

As far as the video issues go, that's odd. RISC iX does seem to use slightly different video timings to RISC OS, as on the Extron video scaler I normally use with my machine, I find myself having to tweak its settings a bit to get a perfect image when I go between RISC iX and RISC OS. I'll double-check with a few other monitors that I have lying around here, but I'm pretty sure that with monitor type 3 (VGA), you should get a usable video signal on more or less anything with a VGA input.

If you've got an oscilloscope and/or frequency counter handy, it'd be very interesting to look at the video H and V sync outputs, and try to figure out exactly *what* about the video timings is making your monitors refuse to sync. I still wonder if it's somehow selecting the wrong VIDC clock and that's throwing off the timings. I suppose since yours is an Adelaide you could just probe the clock pin on the VIDC itself!

2024-12-11 21:05 UTC, MarkYoungIW commented
I do have an Oscilloscope. It's been a long time since I have used it, but I am sure it would do the job. Not convinced I would be able to get under the HCCS Ultimate though to reach the VIDC.

Yeah, I have definitely tried Monitor Type 1+3 several times on all the monitors I have and the TVs through the modulator too, and the same issue. The only monitor that gives any sort of hope is the AFK53 in Type 1+3.

I will try and refresh my memory of what I am doing and get the H+V sync outputs to you as soon as I can.

2024-12-12 00:03 UTC, rhalkyard commented
Just to give you something to visually compare against, I dragged the old boat-anchor scope out and took some measurements of HSync (Pin 14 on a VGA connector), while sitting at the RISC iX console on my A3000. All are at 10 µS/division, positive-edge trigger:

Monitor type 0 (standard): 15KHz
![image](https://github.com/user-attachments/assets/95ea0e8d-0248-4f33-9dfc-be2e5301095b)

Monitor type 1 (multisync): 26KHz
![image](https://github.com/user-attachments/assets/54875d8b-ebaf-4d56-9918-0a1a44108ed7)

Monitor type 3 (VGA): 31KHz
![image](https://github.com/user-attachments/assets/9a6dddfe-3f40-4380-ad73-1bd737939e72)

2024-12-12 00:42 UTC, evansm7 commented
Nice scope :)
@rhalkyard in your RISCiXFS patching did you alter the machine type? I think you must have as there’s the annoying “if OS >2.01 go weird” code that needs working around. 
Anyway, I think your theory of the VIDC enhancer probe code doing bad things on A30x0 is a good one. I have a dim memory that the VIDC enhancer code is _possibly_ predicated on the machine type being FOX/A540; try setting the type to ARCH (numbers in the headers)? At least it’s only a module change… 😩😁

2024-12-12 04:30 UTC, rhalkyard commented
> in your RISCiXFS patching did you alter the machine type? I think you must have as there’s the annoying “if OS >2.01 go weird” code that needs working around.

Nope, the only changes were the DiscOp SWI number, and rewriting the `st` device string to `id`. FWIW my A3000 is running 3.10 and it seems to be OK. Now that you mention it, though, it might be a good idea.

I've come across two versions of `mc_type.h` - the later one seems to suggest that the machine type of 7 used for OS > 2.01 is `MC_UNKNOWN` with the comment: `Later versions of bootstrap program leave it up to us to find out machine type. Will NOT be an A680 or M4.` 

Regardless, it doesn't seem as though changing that to `MC_ARCH` has any impact on its poking of the video control latch. In Arculator at least, both RISC OS and RISC iX seem to write to it regardless of the hardware they're running on - I see the same writes on an emulated A3000. Interestingly, RISC iX always writes `02` (positive sync, 36MHz VIDC clock) at startup, and then writes what appears to be an appropriate value for the mode. `0D` (negative sync, 25.175MHz) for VGA, `00` (positive sync, 25MHz) for multisync. It's possible that this could be an Arculator quirk (kind of like how it emulates backplane IRQ masking on an A3000), I suppose.

@MarkYoungIW one other thing you could try - press F3 once the RISC iX console messages come up, then (without pressing any arrow keys) press + and - on the numeric pad to switch between video modes. Bit of a long shot but worth a go.

2024-12-12 07:38 UTC, MarkYoungIW commented
F3 then +or- is doing something, but unfortunately not stopping the screen rolling.

I will try and dig out my multimeter later on and see what the H+V sync are doing.

![IMG_20241212_073302](https://github.com/user-attachments/assets/ac9fdd99-62ea-4344-bca0-306f2f63db3e)

2024-12-12 17:20 UTC, MarkYoungIW commented
OK, I think I may have to borrow a better Oscilloscope truthfully, as my archaic childs toy doesn't appear up to the job.

However, HSync (Confirm Pin 13 not 14?) appears to be outputting a signal while in RiscOs

![IMG_20241212_171050](https://github.com/user-attachments/assets/2dbf291d-9574-4d6f-8daf-67fea76775c3)

Then the probe clicks back to 'Waiting' (No signal) once the RISCiX terminal takes over the screen.

![IMG_20241212_171434](https://github.com/user-attachments/assets/a3105e41-14a5-456e-bcae-9d7648193d39)

2024-12-12 18:06 UTC, evansm7 commented
Ah! If my phone skimming is right, the thread doesn’t mention sync config (apologies if I’ve missed it). Try this:
`*configure sync 0`
Or, 1. Just not auto, RiX hates auto….

2024-12-12 18:14 UTC, MarkYoungIW commented
Bingo.

*Configure Sync 0 did the job.

I didn't now I need to know the user and password.

![Uploading IMG_20241212_181346.jpg…]()

2024-12-12 18:16 UTC, rhalkyard commented
Hooray! Congratulations on having what could well be the first A3010 to run RISC iX!

Now that Matt jogged my memory, I had some issues with sync settings too, sorry it completely slipped my mind!

`root` / `Tal540bo` should get you in.

2024-12-12 18:20 UTC, MarkYoungIW commented
All looks good.

Thank you for all the help. Always here to do more testing if needed.

![IMG_20241212_181903](https://github.com/user-attachments/assets/9df246b2-c91c-49de-95eb-16144466ebf6)

2024-12-12 18:40 UTC, evansm7 commented
Yay! That xcmap palette looks familiar, nice! This is great.
FWIW I have an A5000 sitting here and some scribbles for adding support for onboard IDE for superio machines – crosses over with your machine because now seems that will enable A3020 too. Hope to have more news in the next few. :)
Fantastic work guys. @rhalkyard merci bucket for another PR, will deal when I’m at a keyboard.

2024-12-12 18:44 UTC, MarkYoungIW commented
Thank you both for your amazing work.

Monitor Type 3 and Sync 0 are just the ticket. Image looks perfect, and it isn't horribly slow either which is quite a nice surprise.